
#
# Toolchain configuration
#

#
# Toolchain info
#
CONFIG_CPU_ARCH="x86_64"
# end of Toolchain info

CONFIG_TOOLCHAIN_PATH=""
CONFIG_TOOLCHAIN_PREFIX=""
CONFIG_TOOLCHAIN_GCCSUFFIX=""
CONFIG_TOOLCHAIN_FLAGS="-D_REENTRANT -I/usr/include/SDL2 -lSDL2"
CONFIG_LIB_LINK_SEARCH_PATH=""
CONFIG_TOOLCHAIN_SYSROOT=""
CONFIG_TOOLCHAIN_SYSTEM_UNIX=y
# CONFIG_TOOLCHAIN_SYSTEM_WIN is not set
CONFIG_EMPTY_SRC_FILE_CPP=y
# CONFIG_EMPTY_SRC_FILE_C is not set
# CONFIG_REPO_AUTOMATION is not set
# CONFIG_COMMPILE_DEBUG is not set
# end of Toolchain configuration

#
# Components configuration
#
# CONFIG_BACKWARD_CPP_ENABLED is not set
# CONFIG_CIMG_COMPONENT_ENABLED is not set
# CONFIG_DEVICE_DRIVER_ENABLED is not set
# CONFIG_LOVYANGFX_ENABLED is not set
# CONFIG_SOEM_ENABLED is not set
# CONFIG_ANYANY_ENABLED is not set
# CONFIG_AXCL_MSP_ENABLED is not set
# CONFIG_C_PERIPHERY_COMPONENT_ENABLED is not set
# CONFIG_CJSON_ENABLED is not set
# CONFIG_COMPONENT1_ENABLED is not set
# CONFIG_CPPSTATE_ENABLED is not set
# CONFIG_EVENTPP_ENABLED is not set
# CONFIG_FFMPEG_VCODE_ENABLED is not set
# CONFIG_LIBFLATBUFFERS_ENABLED is not set
# CONFIG_GPIOD_ENABLED is not set
# CONFIG_LHV_ENABLED is not set
CONFIG_LVGL_COMPONENT_ENABLED=y

#
# lvgl version
#
# CONFIG_LVGL_9_0_SRC is not set
# CONFIG_LVGL_9_3_SRC is not set
CONFIG_LVGL_9_5_SRC=y
# end of lvgl version

#
# LVGL configuration
#
CONFIG_V9_5_LV_CONF_SKIP=y
# CONFIG_V9_5_LV_CONF_MINIMAL is not set

#
# Color Settings
#
# CONFIG_V9_5_LV_COLOR_DEPTH_32 is not set
# CONFIG_V9_5_LV_COLOR_DEPTH_24 is not set
CONFIG_V9_5_LV_COLOR_DEPTH_16=y
# CONFIG_V9_5_LV_COLOR_DEPTH_8 is not set
# CONFIG_V9_5_LV_COLOR_DEPTH_1 is not set
CONFIG_V9_5_LV_COLOR_DEPTH=16
# end of Color Settings

#
# Memory Settings
#
# CONFIG_V9_5_LV_USE_BUILTIN_MALLOC is not set
CONFIG_V9_5_LV_USE_CLIB_MALLOC=y
# CONFIG_V9_5_LV_USE_MICROPYTHON_MALLOC is not set
# CONFIG_V9_5_LV_USE_RTTHREAD_MALLOC is not set
# CONFIG_V9_5_LV_USE_CUSTOM_MALLOC is not set
# CONFIG_V9_5_LV_USE_BUILTIN_STRING is not set
CONFIG_V9_5_LV_USE_CLIB_STRING=y
# CONFIG_V9_5_LV_USE_CUSTOM_STRING is not set
# CONFIG_V9_5_LV_USE_BUILTIN_SPRINTF is not set
CONFIG_V9_5_LV_USE_CLIB_SPRINTF=y
# CONFIG_V9_5_LV_USE_CUSTOM_SPRINTF is not set
# end of Memory Settings

#
# HAL Settings
#
CONFIG_V9_5_LV_DEF_REFR_PERIOD=33
CONFIG_V9_5_LV_DPI_DEF=130
# end of HAL Settings

#
# Operating System (OS)
#
CONFIG_V9_5_LV_OS_NONE=y
# CONFIG_V9_5_LV_OS_PTHREAD is not set
# CONFIG_V9_5_LV_OS_FREERTOS is not set
# CONFIG_V9_5_LV_OS_CMSIS_RTOS2 is not set
# CONFIG_V9_5_LV_OS_RTTHREAD is not set
# CONFIG_V9_5_LV_OS_WINDOWS is not set
# CONFIG_V9_5_LV_OS_MQX is not set
# CONFIG_V9_5_LV_OS_SDL2 is not set
# CONFIG_V9_5_LV_OS_CUSTOM is not set
# end of Operating System (OS)

#
# Rendering Configuration
#
CONFIG_V9_5_LV_DRAW_BUF_STRIDE_ALIGN=1
CONFIG_V9_5_LV_DRAW_BUF_ALIGN=4
CONFIG_V9_5_LV_DRAW_LAYER_SIMPLE_BUF_SIZE=24576
CONFIG_V9_5_LV_DRAW_LAYER_MAX_MEMORY=0
CONFIG_V9_5_LV_USE_DRAW_SW=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_RGB565=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_RGB565_SWAPPED=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_RGB565A8=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_RGB888=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_XRGB8888=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_ARGB8888=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_ARGB8888_PREMULTIPLIED=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_L8=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_AL88=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_A8=y
CONFIG_V9_5_LV_DRAW_SW_SUPPORT_I1=y
CONFIG_V9_5_LV_DRAW_SW_I1_LUM_THRESHOLD=127
CONFIG_V9_5_LV_DRAW_SW_DRAW_UNIT_CNT=1
# CONFIG_V9_5_LV_USE_DRAW_ARM2D_SYNC is not set
# CONFIG_V9_5_LV_USE_NATIVE_HELIUM_ASM is not set
CONFIG_V9_5_LV_DRAW_SW_COMPLEX=y
# CONFIG_V9_5_LV_USE_DRAW_SW_COMPLEX_GRADIENTS is not set
CONFIG_V9_5_LV_DRAW_SW_SHADOW_CACHE_SIZE=0
CONFIG_V9_5_LV_DRAW_SW_CIRCLE_CACHE_SIZE=4
CONFIG_V9_5_LV_DRAW_SW_ASM_NONE=y
# CONFIG_V9_5_LV_DRAW_SW_ASM_NEON is not set
# CONFIG_V9_5_LV_DRAW_SW_ASM_HELIUM is not set
# CONFIG_V9_5_LV_DRAW_SW_ASM_RISCV_V is not set
# CONFIG_V9_5_LV_DRAW_SW_ASM_CUSTOM is not set
CONFIG_V9_5_LV_USE_DRAW_SW_ASM=0
# CONFIG_V9_5_LV_USE_PXP is not set
# CONFIG_V9_5_LV_USE_G2D is not set
# CONFIG_V9_5_LV_USE_DRAW_DAVE2D is not set
# CONFIG_V9_5_LV_USE_DRAW_SDL is not set
# CONFIG_V9_5_LV_USE_DRAW_VG_LITE is not set
# CONFIG_V9_5_LV_USE_VECTOR_GRAPHIC is not set
# CONFIG_V9_5_LV_USE_DRAW_DMA2D is not set
# CONFIG_V9_5_LV_USE_PPA is not set
# CONFIG_V9_5_LV_USE_DRAW_EVE is not set
# end of Rendering Configuration

#
# Feature Configuration
#

#
# Logging
#
# CONFIG_V9_5_LV_USE_LOG is not set
# end of Logging

#
# Asserts
#
CONFIG_V9_5_LV_USE_ASSERT_NULL=y
CONFIG_V9_5_LV_USE_ASSERT_MALLOC=y
# CONFIG_V9_5_LV_USE_ASSERT_STYLE is not set
# CONFIG_V9_5_LV_USE_ASSERT_MEM_INTEGRITY is not set
# CONFIG_V9_5_LV_USE_ASSERT_OBJ is not set
CONFIG_V9_5_LV_ASSERT_HANDLER_INCLUDE="assert.h"
# end of Asserts

#
# Debug
#
# CONFIG_V9_5_LV_USE_REFR_DEBUG is not set
# CONFIG_V9_5_LV_USE_LAYER_DEBUG is not set
# CONFIG_V9_5_LV_USE_PARALLEL_DRAW_DEBUG is not set
# end of Debug

#
# Others
#
# CONFIG_V9_5_LV_ENABLE_GLOBAL_CUSTOM is not set
CONFIG_V9_5_LV_CACHE_DEF_SIZE=0
CONFIG_V9_5_LV_IMAGE_HEADER_CACHE_DEF_CNT=0
CONFIG_V9_5_LV_GRADIENT_MAX_STOPS=2
CONFIG_V9_5_LV_COLOR_MIX_ROUND_OFS=128
# CONFIG_V9_5_LV_OBJ_STYLE_CACHE is not set
# CONFIG_V9_5_LV_USE_OBJ_ID is not set
# CONFIG_V9_5_LV_USE_OBJ_NAME is not set
# CONFIG_V9_5_LV_USE_OBJ_PROPERTY is not set
# CONFIG_V9_5_LV_USE_EXT_DATA is not set
# end of Others
# end of Feature Configuration

#
# Compiler Settings
#
# CONFIG_V9_5_LV_BIG_ENDIAN_SYSTEM is not set
CONFIG_V9_5_LV_ATTRIBUTE_MEM_ALIGN_SIZE=1
# CONFIG_V9_5_LV_ATTRIBUTE_FAST_MEM_USE_IRAM is not set
# CONFIG_V9_5_LV_USE_FLOAT is not set
# CONFIG_V9_5_LV_USE_MATRIX is not set
# CONFIG_V9_5_LV_USE_PRIVATE_API is not set
# end of Compiler Settings

#
# Font Usage
#

#
# Enable built-in fonts
#
# CONFIG_V9_5_LV_FONT_MONTSERRAT_8 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_10 is not set
CONFIG_V9_5_LV_FONT_MONTSERRAT_12=y
CONFIG_V9_5_LV_FONT_MONTSERRAT_14=y
CONFIG_V9_5_LV_FONT_MONTSERRAT_16=y
# CONFIG_V9_5_LV_FONT_MONTSERRAT_18 is not set
CONFIG_V9_5_LV_FONT_MONTSERRAT_20=y
# CONFIG_V9_5_LV_FONT_MONTSERRAT_22 is not set
CONFIG_V9_5_LV_FONT_MONTSERRAT_24=y
# CONFIG_V9_5_LV_FONT_MONTSERRAT_26 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_28 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_30 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_32 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_34 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_36 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_38 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_40 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_42 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_44 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_46 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_48 is not set
# CONFIG_V9_5_LV_FONT_MONTSERRAT_28_COMPRESSED is not set
# CONFIG_V9_5_LV_FONT_DEJAVU_16_PERSIAN_HEBREW is not set
# CONFIG_V9_5_LV_FONT_SOURCE_HAN_SANS_SC_14_CJK is not set
# CONFIG_V9_5_LV_FONT_SOURCE_HAN_SANS_SC_16_CJK is not set
# CONFIG_V9_5_LV_FONT_UNSCII_8 is not set
# CONFIG_V9_5_LV_FONT_UNSCII_16 is not set
# end of Enable built-in fonts

# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_8 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_10 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_12 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_14 is not set
CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_16=y
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_18 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_20 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_22 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_24 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_26 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_28 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_30 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_32 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_34 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_36 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_38 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_40 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_42 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_44 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_46 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_48 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_SOURCE_HAN_SANS_SC_14_CJK is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_SOURCE_HAN_SANS_SC_16_CJK is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_UNSCII_8 is not set
# CONFIG_V9_5_LV_FONT_DEFAULT_UNSCII_16 is not set
# CONFIG_V9_5_LV_FONT_FMT_TXT_LARGE is not set
# CONFIG_V9_5_LV_USE_FONT_COMPRESSED is not set
CONFIG_V9_5_LV_USE_FONT_PLACEHOLDER=y

#
# Enable static fonts
#
# end of Enable static fonts
# end of Font Usage

#
# Text Settings
#
CONFIG_V9_5_LV_TXT_ENC_UTF8=y
# CONFIG_V9_5_LV_TXT_ENC_ASCII is not set
CONFIG_V9_5_LV_TXT_BREAK_CHARS=" ,.;:-_)}"
CONFIG_V9_5_LV_TXT_LINE_BREAK_LONG_LEN=0
CONFIG_V9_5_LV_TXT_COLOR_CMD="#"
# CONFIG_V9_5_LV_USE_BIDI is not set
# CONFIG_V9_5_LV_USE_ARABIC_PERSIAN_CHARS is not set
# end of Text Settings

#
# Widget Usage
#
CONFIG_V9_5_LV_WIDGETS_HAS_DEFAULT_VALUE=y
CONFIG_V9_5_LV_USE_ANIMIMG=y
CONFIG_V9_5_LV_USE_ARC=y
CONFIG_V9_5_LV_USE_ARCLABEL=y
CONFIG_V9_5_LV_USE_BAR=y
CONFIG_V9_5_LV_USE_BUTTON=y
CONFIG_V9_5_LV_USE_BUTTONMATRIX=y
CONFIG_V9_5_LV_USE_CALENDAR=y
# CONFIG_V9_5_LV_CALENDAR_WEEK_STARTS_MONDAY is not set

#
# Days name configuration
#
CONFIG_V9_5_LV_MONDAY_STR="Mo"
CONFIG_V9_5_LV_TUESDAY_STR="Tu"
CONFIG_V9_5_LV_WEDNESDAY_STR="We"
CONFIG_V9_5_LV_THURSDAY_STR="Th"
CONFIG_V9_5_LV_FRIDAY_STR="Fr"
CONFIG_V9_5_LV_SATURDAY_STR="Sa"
CONFIG_V9_5_LV_SUNDAY_STR="Su"
# end of Days name configuration

CONFIG_V9_5_LV_USE_CALENDAR_HEADER_ARROW=y
CONFIG_V9_5_LV_USE_CALENDAR_HEADER_DROPDOWN=y
# CONFIG_V9_5_LV_USE_CALENDAR_CHINESE is not set
CONFIG_V9_5_LV_USE_CANVAS=y
CONFIG_V9_5_LV_USE_CHART=y
CONFIG_V9_5_LV_USE_CHECKBOX=y
CONFIG_V9_5_LV_USE_DROPDOWN=y
CONFIG_V9_5_LV_USE_IMAGE=y
CONFIG_V9_5_LV_USE_IMAGEBUTTON=y
CONFIG_V9_5_LV_USE_KEYBOARD=y
CONFIG_V9_5_LV_USE_LABEL=y
CONFIG_V9_5_LV_LABEL_TEXT_SELECTION=y
CONFIG_V9_5_LV_LABEL_LONG_TXT_HINT=y
CONFIG_V9_5_LV_LABEL_WAIT_CHAR_COUNT=3
CONFIG_V9_5_LV_USE_LED=y
CONFIG_V9_5_LV_USE_LINE=y
CONFIG_V9_5_LV_USE_LIST=y
CONFIG_V9_5_LV_USE_MENU=y
CONFIG_V9_5_LV_USE_MSGBOX=y
CONFIG_V9_5_LV_USE_ROLLER=y
CONFIG_V9_5_LV_USE_SCALE=y
CONFIG_V9_5_LV_USE_SLIDER=y
CONFIG_V9_5_LV_USE_SPAN=y
CONFIG_V9_5_LV_SPAN_SNIPPET_STACK_SIZE=64
CONFIG_V9_5_LV_USE_SPINBOX=y
CONFIG_V9_5_LV_USE_SPINNER=y
CONFIG_V9_5_LV_USE_SWITCH=y
CONFIG_V9_5_LV_USE_TEXTAREA=y
CONFIG_V9_5_LV_TEXTAREA_DEF_PWD_SHOW_TIME=1500
CONFIG_V9_5_LV_USE_TABLE=y
CONFIG_V9_5_LV_USE_TABVIEW=y
CONFIG_V9_5_LV_USE_TILEVIEW=y
CONFIG_V9_5_LV_USE_WIN=y
# end of Widget Usage

#
# Themes
#
CONFIG_V9_5_LV_USE_THEME_DEFAULT=y
# CONFIG_V9_5_LV_THEME_DEFAULT_DARK is not set
CONFIG_V9_5_LV_THEME_DEFAULT_GROW=y
CONFIG_V9_5_LV_THEME_DEFAULT_TRANSITION_TIME=80
CONFIG_V9_5_LV_USE_THEME_SIMPLE=y
# CONFIG_V9_5_LV_USE_THEME_MONO is not set
# end of Themes

#
# Layouts
#
CONFIG_V9_5_LV_USE_FLEX=y
CONFIG_V9_5_LV_USE_GRID=y
# end of Layouts

#
# 3rd Party Libraries
#
CONFIG_V9_5_LV_FS_DEFAULT_DRIVER_LETTER=0
# CONFIG_V9_5_LV_USE_FS_STDIO is not set
CONFIG_V9_5_LV_USE_FS_POSIX=y
CONFIG_V9_5_LV_FS_POSIX_LETTER=65
CONFIG_V9_5_LV_FS_POSIX_PATH="./"
CONFIG_V9_5_LV_FS_POSIX_CACHE_SIZE=4096
# CONFIG_V9_5_LV_USE_FS_WIN32 is not set
# CONFIG_V9_5_LV_USE_FS_FATFS is not set
# CONFIG_V9_5_LV_USE_FS_MEMFS is not set
# CONFIG_V9_5_LV_USE_FS_LITTLEFS is not set
# CONFIG_V9_5_LV_USE_FS_ARDUINO_ESP_LITTLEFS is not set
# CONFIG_V9_5_LV_USE_FS_ARDUINO_SD is not set
# CONFIG_V9_5_LV_USE_FS_UEFI is not set
# CONFIG_V9_5_LV_USE_FS_FROGFS is not set
# CONFIG_V9_5_LV_USE_LODEPNG is not set
# CONFIG_V9_5_LV_USE_LIBPNG is not set
# CONFIG_V9_5_LV_USE_BMP is not set
# CONFIG_V9_5_LV_USE_TJPGD is not set
# CONFIG_V9_5_LV_USE_LIBJPEG_TURBO is not set
# CONFIG_V9_5_LV_USE_LIBWEBP is not set
# CONFIG_V9_5_LV_USE_GIF is not set
# CONFIG_V9_5_LV_BIN_DECODER_RAM_LOAD is not set
# CONFIG_V9_5_LV_USE_RLE is not set
# CONFIG_V9_5_LV_USE_QRCODE is not set
# CONFIG_V9_5_LV_USE_BARCODE is not set
# CONFIG_V9_5_LV_USE_FREETYPE is not set
# CONFIG_V9_5_LV_USE_TINY_TTF is not set
# CONFIG_V9_5_LV_USE_RLOTTIE is not set
# CONFIG_V9_5_LV_USE_THORVG is not set
# CONFIG_V9_5_LV_USE_NANOVG is not set
# CONFIG_V9_5_LV_USE_LZ4 is not set
# CONFIG_V9_5_LV_USE_FFMPEG is not set
# end of 3rd Party Libraries

#
# Others
#
# CONFIG_V9_5_LV_USE_SNAPSHOT is not set
# CONFIG_V9_5_LV_USE_SYSMON is not set
# CONFIG_V9_5_LV_USE_PROFILER is not set
# CONFIG_V9_5_LV_USE_MONKEY is not set
# CONFIG_V9_5_LV_USE_GRIDNAV is not set
# CONFIG_V9_5_LV_USE_FRAGMENT is not set
# CONFIG_V9_5_LV_USE_IMGFONT is not set
CONFIG_V9_5_LV_USE_OBSERVER=y
# CONFIG_V9_5_LV_USE_IME_PINYIN is not set
# CONFIG_V9_5_LV_USE_FILE_EXPLORER is not set
# CONFIG_V9_5_LV_USE_FONT_MANAGER is not set
# CONFIG_V9_5_LV_USE_TEST is not set
# CONFIG_V9_5_LV_USE_TRANSLATION is not set
# CONFIG_V9_5_LV_USE_COLOR_FILTER is not set
CONFIG_V9_5_LVGL_VERSION_MAJOR=9
CONFIG_V9_5_LVGL_VERSION_MINOR=5
CONFIG_V9_5_LVGL_VERSION_PATCH=0
# end of Others

#
# Devices
#
CONFIG_V9_5_LV_USE_SDL=y
CONFIG_V9_5_LV_SDL_INCLUDE_PATH="SDL2/SDL.h"
# CONFIG_V9_5_LV_SDL_RENDER_MODE_PARTIAL is not set
CONFIG_V9_5_LV_SDL_RENDER_MODE_DIRECT=y
# CONFIG_V9_5_LV_SDL_RENDER_MODE_FULL is not set
CONFIG_V9_5_LV_SDL_SINGLE_BUFFER=y
# CONFIG_V9_5_LV_SDL_DOUBLE_BUFFER is not set
CONFIG_V9_5_LV_SDL_BUFFER_COUNT=1
CONFIG_V9_5_LV_SDL_ACCELERATED=y
# CONFIG_V9_5_LV_SDL_FULLSCREEN is not set
CONFIG_V9_5_LV_SDL_DIRECT_EXIT=y
CONFIG_V9_5_LV_SDL_MOUSEWHEEL_MODE_ENCODER=y
# CONFIG_V9_5_LV_SDL_MOUSEWHEEL_MODE_CROWN is not set
CONFIG_V9_5_LV_SDL_MOUSEWHEEL_MODE=0
# CONFIG_V9_5_LV_USE_X11 is not set
# CONFIG_V9_5_LV_USE_WAYLAND is not set
# CONFIG_V9_5_LV_USE_LINUX_FBDEV is not set
# CONFIG_V9_5_LV_USE_NUTTX is not set
# CONFIG_V9_5_LV_USE_LINUX_DRM is not set
# CONFIG_V9_5_LV_USE_TFT_ESPI is not set
# CONFIG_V9_5_LV_USE_LOVYAN_GFX is not set
# CONFIG_V9_5_LV_USE_EVDEV is not set
# CONFIG_V9_5_LV_USE_LIBINPUT is not set
# CONFIG_V9_5_LV_USE_ST7735 is not set
# CONFIG_V9_5_LV_USE_ST7789 is not set
# CONFIG_V9_5_LV_USE_ST7796 is not set
# CONFIG_V9_5_LV_USE_ILI9341 is not set
# CONFIG_V9_5_LV_USE_GENERIC_MIPI is not set
# CONFIG_V9_5_LV_USE_NXP_ELCDIF is not set
# CONFIG_V9_5_LV_USE_RENESAS_GLCDC is not set
# CONFIG_V9_5_LV_USE_ST_LTDC is not set
# CONFIG_V9_5_LV_USE_FT81X is not set
# CONFIG_V9_5_LV_USE_UEFI is not set
# CONFIG_V9_5_LV_USE_QNX is not set
# end of Devices

#
# Examples
#
CONFIG_V9_5_LV_BUILD_EXAMPLES=y
# end of Examples

#
# Demos
#
CONFIG_V9_5_LV_BUILD_DEMOS=y
# CONFIG_V9_5_LV_USE_DEMO_WIDGETS is not set
# CONFIG_V9_5_LV_USE_DEMO_KEYPAD_AND_ENCODER is not set
# CONFIG_V9_5_LV_USE_DEMO_BENCHMARK is not set
# CONFIG_V9_5_LV_USE_DEMO_RENDER is not set
# CONFIG_V9_5_LV_USE_DEMO_STRESS is not set
# CONFIG_V9_5_LV_USE_DEMO_MUSIC is not set
# CONFIG_V9_5_LV_USE_DEMO_FLEX_LAYOUT is not set
# CONFIG_V9_5_LV_USE_DEMO_MULTILANG is not set
# CONFIG_V9_5_LV_USE_DEMO_SMARTWATCH is not set
# CONFIG_V9_5_LV_USE_DEMO_EBIKE is not set
# CONFIG_V9_5_LV_USE_DEMO_HIGH_RES is not set
# end of Demos
# end of LVGL configuration

# CONFIG_MBEDTLS_COMPONENT_ENABLED is not set
# CONFIG_MINICV2_COMPONENT_ENABLED is not set
# CONFIG_MODBUS_ENABLED is not set
# CONFIG_MONGO_C_DRIVER_ENABLED is not set
# CONFIG_NANOJPEG_ENABLED is not set
# CONFIG_NANO_LOG_ENABLED is not set
# CONFIG_NCNN_ENABLED is not set
# CONFIG_LNNG_ENABLED is not set
# CONFIG_QRENCODE_COMPONENT_ENABLED is not set
# CONFIG_SIMDJSON_COMPENENT_ENABLED is not set
# CONFIG_SIMPLEINI_ENABLED is not set
# CONFIG_SINGLE_HEADER_LIBS_ENABLED is not set
# CONFIG_SQLITE3_COMPOENENT_ENABLED is not set
# CONFIG_STATIC_PACKAGE_ENABLED is not set
# CONFIG_STB_ENABLED is not set
# CONFIG_TINYALSA_COMPONENT_ENABLED is not set
# CONFIG_TINY_JPEG_ENABLED is not set
# CONFIG_TOMMATH_ENABLED is not set
# CONFIG_TOOLKIT_ENABLED is not set
# CONFIG_U8G2_COMPONENT_ENABLED is not set
# CONFIG_UNITV2_SUPPORT_ENABLED is not set
# CONFIG_UTILITIES_ENABLED is not set
# CONFIG_ZPL_ENABLED is not set
# CONFIG_MINIAUDIO_COMPONENT_ENABLED is not set
# end of Components configuration

# CONFIG_USE_STRIP_REDUCE_SIZE_ENABLED is not set
