import os

Import("env")
with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

SRCS = Glob("src/*.c*")
INCLUDE = [ADir("."), ADir("include")]
PRIVATE_INCLUDE = []
REQUIREMENTS = ["lvgl_component"]
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = ["-lutil"]
LINK_SEARCH_PATH = []
STATIC_FILES = []

if "CardputerZero" in os.environ:
    project_root = Dir("..").abspath
    sysroot = os.path.join(project_root, "static_lib")
    LINK_SEARCH_PATH = [
        os.path.join(sysroot, "overrides"),
        os.path.join(sysroot, "lib"),
        os.path.join(sysroot, "lib", "aarch64-linux-gnu"),
        os.path.join(sysroot, "usr", "lib"),
        os.path.join(sysroot, "usr", "lib", "aarch64-linux-gnu"),
    ]
    LDFLAGS += [
        f"-Wl,-rpath-link,{os.path.join(sysroot, 'lib')}",
        f"-Wl,-rpath-link,{os.path.join(sysroot, 'lib', 'aarch64-linux-gnu')}",
        f"-Wl,-rpath-link,{os.path.join(sysroot, 'usr', 'lib')}",
        f"-Wl,-rpath-link,{os.path.join(sysroot, 'usr', 'lib', 'aarch64-linux-gnu')}",
    ]

SRCS += append_srcs_dir(ADir("ui"))

lvgl_component = list(
    filter(lambda x: x["target"] == "lvgl_component", env["COMPONENTS"])
)[0]
if "CONFIG_V9_5_LV_USE_SDL" in os.environ:
    lvgl_component["REQUIREMENTS"] += ["SDL2"]
    lvgl_component["INCLUDE"] += ["/usr/include/SDL2"]
    lvgl_component["DEFINITIONS"] += ["-D_REENTRANT"]

env["COMPONENTS"].append(
    {
        "target": "M5CardputerZero-SSHClient",
        "SRCS": SRCS,
        "INCLUDE": INCLUDE,
        "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
        "REQUIREMENTS": REQUIREMENTS,
        "STATIC_LIB": STATIC_LIB,
        "DYNAMIC_LIB": DYNAMIC_LIB,
        "DEFINITIONS": DEFINITIONS,
        "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
        "LDFLAGS": LDFLAGS,
        "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
        "STATIC_FILES": STATIC_FILES,
        "REGISTER": "project",
    }
)
